import { writable } from 'svelte/store';
import shortid from 'shortid';

const encrypt = () => shortid.generate();

export const cardList = writable([
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 'MIN(40px, calc(4px + 2vw))',
        translateY: 0,
        rotate: 6,
        duration: 1,
        icons: [
            {
                id: encrypt(),
                title: 'title!',
                imagePath: '/images/lion.png',
                infos: [
                    {
                        title: '기본 정보',
                        contents: [
                            {
                                type: 'text',
                                title: '이름',
                                content: '리액트 (React)',
                            },
                        ],
                    },
                    {
                        title: '관련 홈페이지',
                        contents: [
                            {
                                type: 'link',
                                title: '초기 세팅하기',
                                content: 'https://zerocho...',
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 'MIN(30px, calc(3px + 1.5vw))',
        translateY: 'MAX(-15px, -0.75vw)',
        rotate: 12,
        duration: 1.2,
    },
    {
        id: encrypt(),
        type: 'blank',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 0,
        translateY: 0,
        rotate: 0,
        duration: 0,
    },
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 'MIN(140px, calc(14px + 7vw))',
        translateY: 0,
        rotate: 8,
        duration: 1.1,
    },
    {
        id: encrypt(),
        type: 'blank',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 0,
        translateY: 0,
        rotate: 0,
        duration: 0,
    },
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 'MAX(-15px, calc(-1.5px - 0.75vw))',
        translateY: 'MAX(-120px, calc(-12px - 6vw))',
        rotate: 21,
        duration: 1.5,
    },
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 0,
        translateY: 0,
        rotate: 4,
        duration: 1,
    },
    {
        id: encrypt(),
        type: 'blank',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 0,
        translateY: 0,
        rotate: 0,
        duration: 0,
    },
    {
        id: encrypt(),
        type: 'card',
        title: 'title!',
        description: 'description!',
        imagePath: '/images/lion.png',
        translateX: 'MIN(20px, calc(2vw - 16px))',
        translateY: 'MAX(-60px, calc(-6px - 3vw))',
        rotate: 23,
        duration: 1.5,
    },
]);
